src/main/java/org/agoncal/application/petstore/model/CreditCardConverter.java
package org.agoncal.application.petstore.model;

public class CreditCardConverter
{
}

src/main/java/org/agoncal/application/petstore/model/CreditCardType.java
package org.agoncal.application.petstore.model;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

public enum CreditCardType
{

   // ======================================
   // =             Constants              =
   // ======================================

   VISA, MASTER_CARD, AMERICAN_EXPRESS
}

src/main/java/org/agoncal/application/petstore/model/OrderLine.java
package org.agoncal.application.petstore.model;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.*;
import javax.validation.constraints.Min;

@Entity
@Table(name = "order_line")
public class OrderLine implements Serializable
{

   // ======================================
   // = Attributes =
   // ======================================

   @Id
   @GeneratedValue(strategy = GenerationType.AUTO)
   @Column(name = "id", updatable = false, nullable = false)
   private Long id;
   @Version
   @Column(name = "version")
   private int version;

   @Column(nullable = false)
   @Min(1)
   private Integer quantity;

   @ManyToOne(cascade = CascadeType.PERSIST)
   @JoinColumn(name = "item_fk", nullable = false)
   private Item item;

   // ======================================
   // = Constructors =
   // ======================================

   public OrderLine()
   {
   }

   public OrderLine(Integer quantity, Item item)
   {
      this.quantity = quantity;
      this.item = item;
   }

   // ======================================
   // = Business methods =
   // ======================================

   public Float getSubTotal()
   {
      return item.getUnitCost() * quantity;
   }

   // ======================================
   // = Getters & setters =
   // ======================================

   public Long getId()
   {
      return this.id;
   }

   public void setId(final Long id)
   {
      this.id = id;
   }

   public int getVersion()
   {
      return this.version;
   }

   public void setVersion(final int version)
   {
      this.version = version;
   }

   public Integer getQuantity()
   {
      return quantity;
   }

   public void setQuantity(Integer quantity)
   {
      this.quantity = quantity;
   }

   public Item getItem()
   {
      return this.item;
   }

   public void setItem(final Item item)
   {
      this.item = item;
   }

   // ======================================
   // = Methods hash, equals, toString =
   // ======================================

   @Override
   public final boolean equals(Object o)
   {
      if (this == o)
         return true;
      if (!(o instanceof OrderLine))
         return false;
      OrderLine orderLine = (OrderLine) o;
      return Objects.equals(quantity, orderLine.quantity) &&
               Objects.equals(item, orderLine.item);
   }

   @Override
   public final int hashCode()
   {
      return Objects.hash(quantity, item);
   }

   @Override
   public String toString()
   {
      return "OrderLine{" +
               "id=" + id +
               ", version=" + version +
               ", quantity=" + quantity +
               ", item=" + item +
               '}';
   }
}

src/main/java/org/agoncal/application/petstore/model/UserRole.java
package org.agoncal.application.petstore.model;

/**
 * @author Antonio Goncalves - http://www.antoniogoncalves.org --
 */
public enum UserRole
{
   // ======================================
   // = Attributes =
   // ======================================

   USER, ADMIN
}

src/main/java/org/agoncal/application/petstore/view/AbstractBean.java
package org.agoncal.application.petstore.view;

import org.agoncal.application.petstore.util.Loggable;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.text.MessageFormat;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Logger;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Loggable
public abstract class AbstractBean {

    // ======================================
    // =             Attributes             =
    // ======================================

    @Inject
    private transient Logger logger;

    // ======================================
    // =          Protected Methods         =
    // ======================================

    private String getMessage(FacesContext facesContext, String msgKey, Object... args) {
        Locale locale = facesContext.getViewRoot().getLocale();
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        ResourceBundle bundle = ResourceBundle.getBundle("Messages", locale, classLoader);
        String msgValue = bundle.getString(msgKey);
        return MessageFormat.format(msgValue, args);
    }

    protected void addInformationMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, getMessage(context, message, args), null));
    }

    protected void addWarningMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, getMessage(context, message, args), null));
    }

    protected void addErrorMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, getMessage(context, message, args), null));
    }

    protected String getParam(String param) {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String, String> map = context.getExternalContext().getRequestParameterMap();
        return map.get(param);
    }

    protected Long getParamId(String param) {
        return Long.valueOf(getParam(param));
    }
}

src/main/java/org/agoncal/application/petstore/view/DebugBean.java
package org.agoncal.application.petstore.view;

import org.agoncal.application.petstore.util.Loggable;

import javax.faces.bean.RequestScoped;
import javax.inject.Named;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Named
@RequestScoped
@Loggable
@CatchException
public class DebugBean extends AbstractBean {

    // ======================================
    // =              Public Methods        =
    // ======================================

    public List<String> getThreadStack() {
        StackTraceElement[] stackTraceElements = Thread.currentThread().getStackTrace();
        List<String> elements = new ArrayList<>();
        for (StackTraceElement stackTraceElement : stackTraceElements) {
            elements.add(stackTraceElement.getClassName() + "." +
                    stackTraceElement.getMethodName() +
                    "(" + stackTraceElement.getFileName() + ":" + stackTraceElement.getLineNumber() + ")");
        }
        return elements;
    }

    public String getWorkingDirectory() {
        return new java.io.File(".").getAbsolutePath();
    }

    public String getTotalMemory() {
        return String.valueOf(Runtime.getRuntime().totalMemory());
    }

    public String getFreeMemory() {
        return String.valueOf(Runtime.getRuntime().freeMemory());
    }
}

src/main/java/org/agoncal/application/petstore/view/LocaleBean.java
package org.agoncal.application.petstore.view;

import org.agoncal.application.petstore.util.Loggable;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Locale;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Named
@SessionScoped
@Loggable
public class LocaleBean implements Serializable {

    @Produces
    private Locale locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();

    // ======================================
    // =          Business methods          =
    // ======================================

    public Locale getLocale() {
        return locale;
    }

    public String getLanguage() {
        return locale.getLanguage();
    }

    public void setLanguage(String language) {
        locale = new Locale(language);
        FacesContext.getCurrentInstance().getViewRoot().setLocale(locale);
    }
}

src/main/java/org/agoncal/application/petstore/view/admin/CategoryBean.java
package org.agoncal.application.petstore.view.admin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.agoncal.application.petstore.model.Category;
import org.agoncal.application.petstore.util.Loggable;

/**
 * Backing bean for Category entities.
 * <p/>
 * This class provides CRUD functionality for all Category entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD framework or
 * custom base class.
 */

@Named
@Stateful
@ConversationScoped
@Loggable
public class CategoryBean implements Serializable
{

   private static final long serialVersionUID = 1L;

   /*
    * Support creating and retrieving Category entities
    */

   private Long id;

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   private Category category;

   public Category getCategory()
   {
      return this.category;
   }

   public void setCategory(Category category)
   {
      this.category = category;
   }

   @Inject
   private Conversation conversation;

   @PersistenceContext(unitName = "applicationPetstorePU", type = PersistenceContextType.EXTENDED)
   private EntityManager entityManager;

   public String create()
   {

      this.conversation.begin();
      this.conversation.setTimeout(1800000L);
      return "create?faces-redirect=true";
   }

   public void retrieve()
   {

      if (FacesContext.getCurrentInstance().isPostback())
      {
         return;
      }

      if (this.conversation.isTransient())
      {
         this.conversation.begin();
         this.conversation.setTimeout(1800000L);
      }

      if (this.id == null)
      {
         this.category = this.example;
      }
      else
      {
         this.category = findById(getId());
      }
   }

   public Category findById(Long id)
   {

      return this.entityManager.find(Category.class, id);
   }

   /*
    * Support updating and deleting Category entities
    */

   public String update()
   {
      this.conversation.end();

      try
      {
         if (this.id == null)
         {
            this.entityManager.persist(this.category);
            return "search?faces-redirect=true";
         }
         else
         {
            this.entityManager.merge(this.category);
            return "view?faces-redirect=true&id=" + this.category.getId();
         }
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   public String delete()
   {
      this.conversation.end();

      try
      {
         Category deletableEntity = findById(getId());

         this.entityManager.remove(deletableEntity);
         this.entityManager.flush();
         return "search?faces-redirect=true";
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   /*
    * Support searching Category entities with pagination
    */

   private int page;
   private long count;
   private List<Category> pageItems;

   private Category example = new Category();

   public int getPage()
   {
      return this.page;
   }

   public void setPage(int page)
   {
      this.page = page;
   }

   public int getPageSize()
   {
      return 10;
   }

   public Category getExample()
   {
      return this.example;
   }

   public void setExample(Category example)
   {
      this.example = example;
   }

   public String search()
   {
      this.page = 0;
      return null;
   }

   public void paginate()
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

      // Populate this.count

      CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
      Root<Category> root = countCriteria.from(Category.class);
      countCriteria = countCriteria.select(builder.count(root)).where(
            getSearchPredicates(root));
      this.count = this.entityManager.createQuery(countCriteria)
            .getSingleResult();

      // Populate this.pageItems

      CriteriaQuery<Category> criteria = builder.createQuery(Category.class);
      root = criteria.from(Category.class);
      TypedQuery<Category> query = this.entityManager.createQuery(criteria
            .select(root).where(getSearchPredicates(root)));
      query.setFirstResult(this.page * getPageSize()).setMaxResults(
            getPageSize());
      this.pageItems = query.getResultList();
   }

   private Predicate[] getSearchPredicates(Root<Category> root)
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
      List<Predicate> predicatesList = new ArrayList<Predicate>();

      String name = this.example.getName();
      if (name != null && !"".equals(name))
      {
         predicatesList.add(builder.like(builder.lower(root.<String> get("name")), '%' + name.toLowerCase() + '%'));
      }
      String description = this.example.getDescription();
      if (description != null && !"".equals(description))
      {
         predicatesList.add(builder.like(builder.lower(root.<String> get("description")), '%' + description.toLowerCase() + '%'));
      }

      return predicatesList.toArray(new Predicate[predicatesList.size()]);
   }

   public List<Category> getPageItems()
   {
      return this.pageItems;
   }

   public long getCount()
   {
      return this.count;
   }

   /*
    * Support listing and POSTing back Category entities (e.g. from inside an
    * HtmlSelectOneMenu)
    */

   public List<Category> getAll()
   {

      CriteriaQuery<Category> criteria = this.entityManager
            .getCriteriaBuilder().createQuery(Category.class);
      return this.entityManager.createQuery(
            criteria.select(criteria.from(Category.class))).getResultList();
   }

   @Resource
   private SessionContext sessionContext;

   public Converter getConverter()
   {

      final CategoryBean ejbProxy = this.sessionContext.getBusinessObject(CategoryBean.class);

      return new Converter()
      {

         @Override
         public Object getAsObject(FacesContext context,
               UIComponent component, String value)
         {

            return ejbProxy.findById(Long.valueOf(value));
         }

         @Override
         public String getAsString(FacesContext context,
               UIComponent component, Object value)
         {

            if (value == null)
            {
               return "";
            }

            return String.valueOf(((Category) value).getId());
         }
      };
   }

   /*
    * Support adding children to bidirectional, one-to-many tables
    */

   private Category add = new Category();

   public Category getAdd()
   {
      return this.add;
   }

   public Category getAdded()
   {
      Category added = this.add;
      this.add = new Category();
      return added;
   }
}

src/main/webapp/shopping/confirmorder.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                xmlns:forgeview="http://jboss.org/forge/view"
                template="/resources/templates/templateShopping.xhtml">

    <ui:param name="pageTitle" value="#{i18n.orderConfirmed_yourOrderIsComplete}"/>

    <ui:define name="header">
        #{i18n.orderConfirmed_yourOrderIsComplete}
    </ui:define>

    <ui:define name="main">

        <h:form>

            <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">#{i18n.confirmorder_personalInformation}</h3>
            </div>
            <div class="panel-body">
                <h:panelGrid columns="3">
                    <h:outputText value="#{i18n.customer_firstName}:"/>
                    <h:inputText id="firstName" value="#{shoppingCartBean.customer.firstName}" readonly="true" class="form-control"/>
                    <h:message for="firstName" style="color: red;"/>

                    <h:outputText value="#{i18n.customer_lastName}:"/>
                    <h:inputText id="lastName" value="#{shoppingCartBean.customer.lastName}" readonly="true" class="form-control"/>
                    <h:message for="lastName" style="color: red;"/>

                    <h:outputText value="#{i18n.customer_email}:"/>
                    <h:inputText id="email" value="#{shoppingCartBean.customer.email}" readonly="true" class="form-control"/>
                    <h:message for="email" style="color: red;"/>

                </h:panelGrid>
            </div>
            </div>

            <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">#{i18n.confirmorder_deliveryAddress}</h3>
            </div>
            <div class="panel-body">
                <h:panelGrid columns="3">
                    <h:outputText value="* #{i18n.address_street1}:"/>
                    <h:inputText id="street1" value="#{shoppingCartBean.customer.homeAddress.street1}" class="form-control"/>
                    <h:message for="street1" style="color: red;"/>

                    <h:outputText value="#{i18n.address_street2}:"/>
                    <h:inputText id="street2" value="#{shoppingCartBean.customer.homeAddress.street2}" class="form-control"/>
                    <h:message for="street2" style="color: red;"/>

                    <h:outputText value="* #{i18n.address_city}:"/>
                    <h:inputText id="city" value="#{shoppingCartBean.customer.homeAddress.city}" class="form-control"/>
                    <h:message for="city" style="color: red;"/>

                    <h:outputText value="#{i18n.address_state}:"/>
                    <h:inputText id="state" value="#{shoppingCartBean.customer.homeAddress.state}" class="form-control"/>
                    <h:message for="state" style="color: red;"/>

                    <h:outputText value="* #{i18n.address_zipcode}:"/>
                    <h:inputText id="zipcode" value="#{shoppingCartBean.customer.homeAddress.zipcode}" class="form-control"/>
                    <h:message for="zipcode" style="color: red;"/>

                    <h:outputText value="* #{i18n.address_country}:"/>
                    <h:selectOneMenu id="country"  converter="#{countryBean.converter}" value="#{shoppingCartBean.customer.homeAddress.country}" class="form-control">
                        <f:selectItem/>
                        <f:selectItems itemLabel="#{forgeview:display(_item)}" itemValue="#{_item}" value="#{countryBean.all}" var="_item"/>
                    </h:selectOneMenu>
                    <h:message for="country" style="color: red;"/>

                </h:panelGrid>
            </div>
            </div>

            <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">#{i18n.creditCard}</h3>
            </div>
            <div class="panel-body">
                <h:panelGrid columns="3">
                    <h:outputText value="* #{i18n.creditCard_creditCardNumber}:"/>
                    <h:inputText id="creditCardNumber" value="#{shoppingCartBean.creditCard.creditCardNumber}" class="form-control"/>
                    <h:message for="creditCardNumber" style="color: red;"/>

                    <h:outputText value="* #{i18n.creditCard_creditCardType}:"/>
                    <h:selectOneMenu value="#{shoppingCartBean.creditCard.creditCardType}" class="form-control">
                        <f:selectItems value="#{shoppingCartBean.creditCardTypes}"/>
                    </h:selectOneMenu>
                    <h:outputText value=""/>

                    <h:outputText value="* #{i18n.creditCard_creditCardExpDate} (MM/YY):"/>
                    <h:inputText id="creditCardExpDate" value="#{shoppingCartBean.creditCard.creditCardExpDate}"  class="form-control"/>
                    <h:message for="creditCardExpDate" style="color: red;"/>
                </h:panelGrid>
            </div>
            </div>

            <div>
                <h:commandButton value="#{i18n.submit}" action="#{shoppingCartBean.confirmOrder}" type="submit"
                                 class="btn btn-primary"/>
            </div>
        </h:form>

    </ui:define>
</ui:composition>

src/main/webapp/shopping/main.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                template="/resources/templates/templateShopping.xhtml">

    <ui:param name="pageTitle" value="YAPS PetStore"/>

    <ui:define name="main">
        <div style="text-align: center; margin-top:50px;">
            <map name="pestoremap">
                <area alt="Birds" coords="72,2,280,250" shape="RECT" href="showproducts.xhtml?categoryName=Birds"/>
                <area alt="Fish" coords="2,180,72,250" shape="RECT" href="showproducts.xhtml?categoryName=Fish"/>
                <area alt="Dogs" coords="60,250,130,320" shape="RECT" href="showproducts.xhtml?categoryName=Dogs"/>
                <area alt="Reptiles" coords="140,270,210,340" shape="RECT"
                      href="showproducts.xhtml?categoryName=Reptiles"/>
                <area alt="Cats" coords="225,240,295,310" shape="RECT" href="showproducts.xhtml?categoryName=Cats"/>
                <area alt="Birds" coords="280,180,350,250" shape="RECT" href="showproducts.xhtml?categoryName=Birds"/>
            </map>
            <img src="#{resource['splash.gif']}" border="0" width="350" height="355" align="middle" usemap="#pestoremap"
                 alt="Welcome to YAPS PetStore"/>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/shopping/orderconfirmed.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/resources/templates/templateShopping.xhtml">

    <ui:param name="pageTitle" value="#{i18n.orderConfirmed_yourOrderIsComplete}"/>

    <ui:define name="header">
        #{i18n.orderConfirmed_yourOrderIsComplete}
    </ui:define>

    <ui:define name="main">

        <h:form>
            <h:dataTable value="#{shoppingCartBean.order.orderLines}" var="orderLine" styleClass="table">
                <h:column>
                    <strong><h:outputText value="#{orderLine.item.product.name}"/></strong>
                    <br/>
                    <h:outputText value="#{orderLine.item.name}"/>
                </h:column>
                <h:column>
                    <h:outputText value="#{orderLine.quantity}"/>
                </h:column>
                <h:column>
                    x
                    <h:outputText value="#{orderLine.item.unitCost}"/>
                    $
                </h:column>
                <h:column>
                    =
                    <h:outputText value="#{orderLine.subTotal}"/>
                    $
                </h:column>
            </h:dataTable>
            <br/>

            <div style="margin-top: 20px; font-weight: bold;">
                Total $ #{shoppingCartBean.order.total}
            </div>
        </h:form>

        <legend>#{i18n.orderConfirmed_yourOrderIdIs} : #{shoppingCartBean.order.id}</legend>

        <p style="margin-top: 15px">#{i18n.orderConfirmed_msg1}</p>

        <p style="margin-top: 15px">#{i18n.orderConfirmed_msg2}</p>

    </ui:define>
</ui:composition>

src/main/webapp/shopping/searchresult.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="/resources/templates/templateShopping.xhtml">

    <f:metadata>
        <f:viewParam name="keyword" value="#{catalogBean.keyword}"/>
        <f:viewAction action="#{catalogBean.doSearch}"/>
    </f:metadata>

    <ui:param name="pageTitle" value="#{i18n.searchResult_searchFor} #{catalogBean.keyword}"/>

    <ui:define name="header">
        #{i18n.searchResult_searchFor} : #{catalogBean.keyword}
    </ui:define>

    <ui:define name="subheader">
        <h:outputText value="#{i18n.noItemsFound}"
                      rendered="#{catalogBean.items == null || catalogBean.items.size() ==0}"/>
    </ui:define>

    <ui:define name="main">

        <h:dataTable value="#{catalogBean.items}" var="oneItem" rendered="#{catalogBean.items.size() > 0}"
                     styleClass="table">
            <h:column>
                <h:graphicImage url="/resources/images/#{oneItem.imagePath}" alt="Item"/>
            </h:column>

            <h:column>
                <h:link outcome="showitem" includeViewParams="true" value="#{oneItem.name}">
                    <f:param name="itemId" value="#{oneItem.id}"/>
                    <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                </h:link>
            </h:column>

            <h:column>
                <em>(
                    <h:outputText value="#{oneItem.product.category.name}"/>
                    -
                    <h:outputText value="#{oneItem.product.name}"/>
                    )</em>
            </h:column>
            <h:column>
                <h:outputText value="#{oneItem.unitCost}"/> $
            </h:column>

            <h:column>
                <h:form>
                    <h:commandLink action="#{shoppingCartBean.addItemToCart}" styleClass="add-to-cart"
                                   rendered="#{accountBean.loggedIn}">
                        <h:outputText value="#{i18n.searchResult_addToCart}"/>
                        <f:param name="itemId" value="#{oneItem.id}"/>
                    </h:commandLink>
                </h:form>
            </h:column>
        </h:dataTable>

    </ui:define>
</ui:composition>

src/main/webapp/shopping/showcart.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="/resources/templates/templateShopping.xhtml">

    <ui:param name="pageTitle" value="#{i18n.shoppingCart}"/>

    <ui:define name="header">
        #{i18n.shoppingCart}
    </ui:define>

    <ui:define name="subheader">
        <h:outputText value="#{i18n.shoppingCart_empty}" rendered="#{shoppingCartBean.shoppingCartIsEmpty()}"/>
    </ui:define>

    <ui:define name="main">

        <h:form rendered="#{!shoppingCartBean.shoppingCartIsEmpty()}">
            <h:dataTable value="#{shoppingCartBean.cartItems}" var="oneItem" styleClass="table">
                <h:column>
                    <h:outputText value="#{oneItem.item.product.name}"/>
                    <br/>
                    <h:commandLink action="#{catalogBean.doFindItem}">
                        <h:outputText value="#{oneItem.item.name}"/>
                        <f:param name="itemId" value="#{oneItem.item.id}"/>
                    </h:commandLink>
                </h:column>
                <h:column>
                    <h:commandLink action="#{shoppingCartBean.updateQuantity}" styleClass="arrow_refresh">
                        <h:outputText value="#{i18n.update}"/>
                        <f:param name="itemId" value="#{oneItem.item.id}"/>
                    </h:commandLink>
                </h:column>
                <h:column>
                    <h:inputText value="#{oneItem.quantity}"/>
                </h:column>
                <h:column>
                    x
                    <h:outputText value="#{oneItem.item.unitCost}"/> $
                </h:column>
                <h:column>
                    = <h:outputText value="#{oneItem.subTotal}"/> $
                </h:column>
                <h:column>
                    <h:commandLink action="#{shoppingCartBean.removeItemFromCart}" styleClass="remove-from-cart">
                        <h:outputText value="#{i18n.remove}"/>
                        <f:param name="itemId" value="#{oneItem.item.id}"/>
                    </h:commandLink>
                </h:column>
            </h:dataTable>

            <br/>

            <div>
                Total $
                <h:outputText value="#{shoppingCartBean.total}"/>
                <h:commandLink action="#{shoppingCartBean.checkout}" value="Check Out"
                               styleClass="checkout-cart"/>
            </div>
        </h:form>

    </ui:define>
</ui:composition>