src/main/java/org/agoncal/application/petstore/view/admin/ItemBean.java
package org.agoncal.application.petstore.view.admin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.agoncal.application.petstore.model.Item;
import org.agoncal.application.petstore.model.Product;
import org.agoncal.application.petstore.util.Loggable;

/**
 * Backing bean for Item entities.
 * <p/>
 * This class provides CRUD functionality for all Item entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD framework or
 * custom base class.
 */

@Named
@Stateful
@ConversationScoped
@Loggable
public class ItemBean implements Serializable
{

   private static final long serialVersionUID = 1L;

   /*
    * Support creating and retrieving Item entities
    */

   private Long id;

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   private Item item;

   public Item getItem()
   {
      return this.item;
   }

   public void setItem(Item item)
   {
      this.item = item;
   }

   @Inject
   private Conversation conversation;

   @PersistenceContext(unitName = "applicationPetstorePU", type = PersistenceContextType.EXTENDED)
   private EntityManager entityManager;

   public String create()
   {

      this.conversation.begin();
      this.conversation.setTimeout(1800000L);
      return "create?faces-redirect=true";
   }

   public void retrieve()
   {

      if (FacesContext.getCurrentInstance().isPostback())
      {
         return;
      }

      if (this.conversation.isTransient())
      {
         this.conversation.begin();
         this.conversation.setTimeout(1800000L);
      }

      if (this.id == null)
      {
         this.item = this.example;
      }
      else
      {
         this.item = findById(getId());
      }
   }

   public Item findById(Long id)
   {

      return this.entityManager.find(Item.class, id);
   }

   /*
    * Support updating and deleting Item entities
    */

   public String update()
   {
      this.conversation.end();

      try
      {
         if (this.id == null)
         {
            this.entityManager.persist(this.item);
            return "search?faces-redirect=true";
         }
         else
         {
            this.entityManager.merge(this.item);
            return "view?faces-redirect=true&id=" + this.item.getId();
         }
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   public String delete()
   {
      this.conversation.end();

      try
      {
         Item deletableEntity = findById(getId());

         this.entityManager.remove(deletableEntity);
         this.entityManager.flush();
         return "search?faces-redirect=true";
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   /*
    * Support searching Item entities with pagination
    */

   private int page;
   private long count;
   private List<Item> pageItems;

   private Item example = new Item();

   public int getPage()
   {
      return this.page;
   }

   public void setPage(int page)
   {
      this.page = page;
   }

   public int getPageSize()
   {
      return 10;
   }

   public Item getExample()
   {
      return this.example;
   }

   public void setExample(Item example)
   {
      this.example = example;
   }

   public String search()
   {
      this.page = 0;
      return null;
   }

   public void paginate()
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

      // Populate this.count

      CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
      Root<Item> root = countCriteria.from(Item.class);
      countCriteria = countCriteria.select(builder.count(root)).where(
            getSearchPredicates(root));
      this.count = this.entityManager.createQuery(countCriteria)
            .getSingleResult();

      // Populate this.pageItems

      CriteriaQuery<Item> criteria = builder.createQuery(Item.class);
      root = criteria.from(Item.class);
      TypedQuery<Item> query = this.entityManager.createQuery(criteria
            .select(root).where(getSearchPredicates(root)));
      query.setFirstResult(this.page * getPageSize()).setMaxResults(
            getPageSize());
      this.pageItems = query.getResultList();
   }

   private Predicate[] getSearchPredicates(Root<Item> root)
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
      List<Predicate> predicatesList = new ArrayList<Predicate>();

      String name = this.example.getName();
      if (name != null && !"".equals(name))
      {
         predicatesList.add(builder.like(builder.lower(root.<String> get("name")), '%' + name.toLowerCase() + '%'));
      }
      String description = this.example.getDescription();
      if (description != null && !"".equals(description))
      {
         predicatesList.add(builder.like(builder.lower(root.<String> get("description")), '%' + description.toLowerCase() + '%'));
      }
      String imagePath = this.example.getImagePath();
      if (imagePath != null && !"".equals(imagePath))
      {
         predicatesList.add(builder.like(builder.lower(root.<String> get("imagePath")), '%' + imagePath.toLowerCase() + '%'));
      }
      Product product = this.example.getProduct();
      if (product != null)
      {
         predicatesList.add(builder.equal(root.get("product"), product));
      }

      return predicatesList.toArray(new Predicate[predicatesList.size()]);
   }

   public List<Item> getPageItems()
   {
      return this.pageItems;
   }

   public long getCount()
   {
      return this.count;
   }

   /*
    * Support listing and POSTing back Item entities (e.g. from inside an
    * HtmlSelectOneMenu)
    */

   public List<Item> getAll()
   {

      CriteriaQuery<Item> criteria = this.entityManager
            .getCriteriaBuilder().createQuery(Item.class);
      return this.entityManager.createQuery(
            criteria.select(criteria.from(Item.class))).getResultList();
   }

   @Resource
   private SessionContext sessionContext;

   public Converter getConverter()
   {

      final ItemBean ejbProxy = this.sessionContext.getBusinessObject(ItemBean.class);

      return new Converter()
      {

         @Override
         public Object getAsObject(FacesContext context,
               UIComponent component, String value)
         {

            return ejbProxy.findById(Long.valueOf(value));
         }

         @Override
         public String getAsString(FacesContext context,
               UIComponent component, Object value)
         {

            if (value == null)
            {
               return "";
            }

            return String.valueOf(((Item) value).getId());
         }
      };
   }

   /*
    * Support adding children to bidirectional, one-to-many tables
    */

   private Item add = new Item();

   public Item getAdd()
   {
      return this.add;
   }

   public Item getAdded()
   {
      Item added = this.add;
      this.add = new Item();
      return added;
   }
}

src/main/webapp/resources/templates/paginator.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:fn="http://xmlns.jcp.org/jsp/jstl/functions"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
	
	<h:panelGroup styleClass="paginator" rendered="#{paginatorBean.count gt paginatorBean.pageSize}">
		<!-- Use commandLink, not outputLink, so that search criteria is not lost -->
		<h:commandLink styleClass="btn btn-primary" rendered="#{paginatorBean.page gt 0}">
			<f:param name="page" value="#{paginatorBean.page - 1}"/>
			&lt; Previous 
		</h:commandLink>
		<h:outputText styleClass="paginator-content" value="#{paginatorBean.page * paginatorBean.pageSize + 1} to #{paginatorBean.page * paginatorBean.pageSize + fn:length(paginatorBean.pageItems)} (of #{paginatorBean.count})"/>
		<h:commandLink styleClass="btn btn-primary" rendered="#{(paginatorBean.page + 1) * paginatorBean.pageSize lt paginatorBean.count}">
			<f:param name="page" value="#{paginatorBean.page + 1}"/>
			Next &gt;
		</h:commandLink>
	</h:panelGroup>

</ui:composition>

src/main/webapp/resources/templates/template.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
        xmlns:h="http://xmlns.jcp.org/jsf/html"
        xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
      xmlns:p="http://primefaces.org/ui">
<f:view contentType="text/html" encoding="UTF-8">

    <!--HEAD-->
    <h:head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content=""/>
        <meta name="author" content=""/>
        <title>#{empty pageTitle ? 'Page Title' : pageTitle}</title>
        <link rel="icon" href="#{resource['favicon.gif']}"/>
        <link rel="shortcut icon" href="#{resource['favicon.gif']}"/>

        <!-- Bootstrap core CSS -->
        <h:outputStylesheet library="webjars" name="bootstrap/3.3.7-1/css/bootstrap.min.css"/>


        <!-- Custom styles for this template -->
        <h:outputStylesheet name="css/style.css"/>
        <h:outputStylesheet name="css/sticky-footer-navbar.css"/>
    </h:head>

    <!--BODY-->
    <h:body>

        <!-- Wrap all page content here -->
        <div id="wrap">

            <!-- Fixed navbar -->
            <h:form>
                <div class="navbar navbar-default navbar-fixed-top" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <h:link class="navbar-brand" outcome="/shopping/main" value="Yaps Petstore EE 7">
                                <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                            </h:link>
                        </div>

                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav">
                                <li>
                                    <h:link outcome="/admin/category/search" value="Admin"/>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Languages<b
                                            class="caret"></b></a>
                                    <ul class="dropdown-menu">
                                        <li>
                                            <h:commandLink action="#{localeBean.setLanguage('fr')}" styleClass="menu-fr"
                                                           immediate="true">
                                                <f:ajax render="@form"/>
                                                <h:outputText value="Français"/>
                                            </h:commandLink>
                                        </li>
                                        <li>
                                            <h:commandLink action="#{localeBean.setLanguage('en')}" styleClass="menu-en"
                                                           immediate="true">
                                                <f:ajax render="@form"/>
                                                <h:outputText value="English"/>
                                            </h:commandLink>
                                        </li>
                                    </ul>
                                </li>
                            </ul>
                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <!--<i class="icon-user icon-white"></i>-->
                                    <h:link outcome="/shopping/showaccount"
                                            value="#{i18n.welcome} #{accountBean.loggedinCustomer.firstName}"
                                            rendered="#{accountBean.loggedIn}">
                                        <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                                    </h:link>
                                </li>
                                <li>
                                    <!--<i class="icon-off icon-white"></i>-->
                                    <h:commandLink action="#{accountBean.doLogout}"
                                                   rendered="#{accountBean.loggedIn}">
                                        <h:outputText value="${i18n.logOut}"/>
                                    </h:commandLink>
                                </li>
                                <li>
                                    <!--<i class="icon-eye-open icon-white"></i>-->
                                    <h:link outcome="/shopping/signon" value="#{i18n.logIn}"
                                            rendered="#{!accountBean.loggedIn}">
                                        <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                                    </h:link>
                                </li>
                                <li>
                                    <!--<i class="icon-shopping-cart icon-white"></i>-->
                                    <h:link outcome="/shopping/showcart" value="#{i18n.shoppingCart}"
                                            rendered="#{!shoppingCartBean.shoppingCartIsEmpty()}">
                                        <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                                    </h:link>
                                </li>

                                <li>
                                    <div class="navbar-form navbar-left" role="search">
                                        <div class="form-group">
                                            <h:inputText class="form-control" value="#{catalogBean.keyword}"/>
                                        </div>
                                        <h:commandButton action="#{catalogBean.doSearch}" value="#{i18n.search}"
                                                         class="btn btn-default"/>
                                    </div>
                                </li>
                            </ul>
                        </div>
                        <!--/.nav-collapse -->
                    </div>
                </div>
            </h:form>

            <!-- Begin page content -->
            <div class="container">
                <div class="page-header">
                    <!-- Error messages-->
                    <h:messages globalOnly="true" errorClass="alert alert-error" warnClass="alert"
                                infoClass="alert alert-info"/>
                </div>

                <ui:insert name="navigation">Default navigation</ui:insert>

                <!-- CONTENT -->
                <div class="col-md-1"/>
                <div class="col-md-9 well">
                    <h2><ui:insert name="header"/></h2>

                    <h3><ui:insert name="subheader"/></h3>

                    <ui:insert name="main"/>
                </div>
                <!--/.CONTENT -->

            </div>
        </div>

        <div id="footer">
            <div class="container">
                <div class="col-md-2 centered-text">
                    <a href="https://github.com/agoncal/agoncal-application-petstore-ee7">Source code on GitHub</a>
                    <br/>
                    <a href="http://www.antoniogoncalves.org">Antonio Goncalves</a>
                </div>
                <div class="col-md-8"/>
                <div class="col-md-2 centered-text">
                    <a href="/applicationPetstore/swagger.json">Swagger Contract</a>
                    <br/>
                    <h:outputText value="Conversation [#{shoppingCartBean.conversation.id}]"/>
                </div>
            </div>
        </div>


        <!-- Bootstrap core JavaScript
       ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <h:outputScript library="webjars" name="jquery/2.2.4/jquery.min.js"/>
        <h:outputScript library="webjars" name="bootstrap/3.3.7-1/js/bootstrap.min.js"/>
        <h:outputScript target="head">
            // Add the $() function
            $ = jQuery;
            $(document).ready(function () {
                jQuery.noConflict();
            });
        </h:outputScript>
    </h:body>
</f:view>
</html>

src/main/webapp/resources/templates/templateCRUD.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                template="/resources/templates/template.xhtml">

    <ui:define name="navigation">
        <div class="col-md-2 well">
            <ul class="nav nav-list">
                <li><h3><h:link outcome="/admin/category/search" value="Category"/></h3></li>
                <li><h3><h:link outcome="/admin/country/search" value="Country"/></h3></li>
                <li><h3><h:link outcome="/admin/customer/search" value="Customer"/></h3></li>
                <li><h3><h:link outcome="/admin/item/search" value="Item"/></h3></li>
                <li><h3><h:link outcome="/admin/product/search" value="Product"/></h3></li>
                <li><h3><h:link outcome="/admin/purchaseOrder/search" value="Order"/></h3></li>
            </ul>
        </div>
    </ui:define>
</ui:composition>

src/main/webapp/resources/templates/templateShopping.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core"
                template="/resources/templates/template.xhtml">

    <ui:define name="navigation">
        <div class="col-md-2 well">
            <ul class="nav nav-list">
                <li><h3><h:link outcome="/shopping/showproducts" value="Fish">
                    <f:param name="categoryName" value="Fish"/>
                    <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                </h:link></h3>
                </li>
                <li><h3><h:link outcome="/shopping/showproducts" value="Dogs">
                    <f:param name="categoryName" value="Dogs"/>
                    <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                </h:link></h3>
                </li>
                <li><h3><h:link outcome="/shopping/showproducts" value="Reptiles">
                    <f:param name="categoryName" value="Reptiles"/>
                    <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                </h:link></h3>
                </li>
                <li><h3><h:link outcome="/shopping/showproducts" value="Cats">
                    <f:param name="categoryName" value="Cats"/>
                    <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                </h:link></h3>
                </li>
                <li><h3><h:link outcome="/shopping/showproducts" value="Birds">
                    <f:param name="categoryName" value="Birds"/>
                    <!--<f:param name="cid" value="#{javax.enterprise.context.conversation.id}"/>-->
                </h:link></h3>
                </li>
            </ul>
        </div>
    </ui:define>
</ui:composition>