src/main/java/org/agoncal/application/petstore/model/Address.java
package org.agoncal.application.petstore.model;

import java.io.Serializable;
import java.util.Objects;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * @author Antonio Goncalves http://www.antoniogoncalves.org --
 */

@Embeddable
public class Address implements Serializable
{

   // ======================================
   // = Attributes =
   // ======================================

   @Column(length = 50, nullable = false)
   @Size(min = 5, max = 50)
   @NotNull
   private String street1;

   @Column
   private String street2;

   @Column(length = 50, nullable = false)
   @Size(min = 2, max = 50)
   @NotNull
   private String city;

   @Column
   private String state;

   @Column(length = 10, name = "zip_code", nullable = false)
   @Size(min = 1, max = 10)
   @NotNull
   private String zipcode;

   @ManyToOne(cascade = CascadeType.PERSIST)
   private Country country = new Country();

   // ======================================
   // = Constructors =
   // ======================================

   public Address()
   {
   }

   public Address(String street1, String city, String zipcode, Country country)
   {
      this.street1 = street1;
      this.city = city;
      this.zipcode = zipcode;
      this.country = country;
   }

   // ======================================
   // = Getters & setters =
   // ======================================

   public String getStreet1()
   {
      return street1;
   }

   public void setStreet1(String street1)
   {
      this.street1 = street1;
   }

   public String getStreet2()
   {
      return street2;
   }

   public void setStreet2(String street2)
   {
      this.street2 = street2;
   }

   public String getCity()
   {
      return city;
   }

   public void setCity(String city)
   {
      this.city = city;
   }

   public String getState()
   {
      return state;
   }

   public void setState(String state)
   {
      this.state = state;
   }

   public String getZipcode()
   {
      return zipcode;
   }

   public void setZipcode(String zipcode)
   {
      this.zipcode = zipcode;
   }

   public Country getCountry()
   {
      return this.country;
   }

   public void setCountry(final Country country)
   {
      this.country = country;
   }

   // ======================================
   // = Methods hash, equals, toString =
   // ======================================

   @Override
   public final boolean equals(Object o)
   {
      if (this == o)
         return true;
      if (!(o instanceof Address))
         return false;
      Address address = (Address) o;
      return Objects.equals(street1, address.street1) &&
               Objects.equals(city, address.city) &&
               Objects.equals(state, address.state) &&
               Objects.equals(zipcode, address.zipcode) &&
               Objects.equals(country, address.country);
   }

   @Override
   public final int hashCode()
   {
      return Objects.hash(street1, city, state, zipcode, country);
   }

   @Override
   public String toString()
   {
      return "Address{" +
               "street1='" + street1 + '\'' +
               ", street2='" + street2 + '\'' +
               ", city='" + city + '\'' +
               ", state='" + state + '\'' +
               ", zipcode='" + zipcode + '\'' +
               ", country=" + country +
               '}';
   }
}

src/main/java/org/agoncal/application/petstore/model/CreditCardConverter.java
package org.agoncal.application.petstore.model;

public class CreditCardConverter
{
}

src/main/java/org/agoncal/application/petstore/model/CreditCardType.java
package org.agoncal.application.petstore.model;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

public enum CreditCardType
{

   // ======================================
   // =             Constants              =
   // ======================================

   VISA, MASTER_CARD, AMERICAN_EXPRESS
}

src/main/java/org/agoncal/application/petstore/model/UserRole.java
package org.agoncal.application.petstore.model;

/**
 * @author Antonio Goncalves - http://www.antoniogoncalves.org --
 */
public enum UserRole
{
   // ======================================
   // = Attributes =
   // ======================================

   USER, ADMIN
}

src/main/java/org/agoncal/application/petstore/view/AbstractBean.java
package org.agoncal.application.petstore.view;

import org.agoncal.application.petstore.util.Loggable;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.text.MessageFormat;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.logging.Logger;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Loggable
public abstract class AbstractBean {

    // ======================================
    // =             Attributes             =
    // ======================================

    @Inject
    private transient Logger logger;

    // ======================================
    // =          Protected Methods         =
    // ======================================

    private String getMessage(FacesContext facesContext, String msgKey, Object... args) {
        Locale locale = facesContext.getViewRoot().getLocale();
        ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
        ResourceBundle bundle = ResourceBundle.getBundle("Messages", locale, classLoader);
        String msgValue = bundle.getString(msgKey);
        return MessageFormat.format(msgValue, args);
    }

    protected void addInformationMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, getMessage(context, message, args), null));
    }

    protected void addWarningMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, getMessage(context, message, args), null));
    }

    protected void addErrorMessage(String message, Object... args) {
        FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_ERROR, getMessage(context, message, args), null));
    }

    protected String getParam(String param) {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String, String> map = context.getExternalContext().getRequestParameterMap();
        return map.get(param);
    }

    protected Long getParamId(String param) {
        return Long.valueOf(getParam(param));
    }
}

src/main/java/org/agoncal/application/petstore/view/DebugBean.java
package org.agoncal.application.petstore.view;

import org.agoncal.application.petstore.util.Loggable;

import javax.faces.bean.RequestScoped;
import javax.inject.Named;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Named
@RequestScoped
@Loggable
@CatchException
public class DebugBean extends AbstractBean {

    // ======================================
    // =              Public Methods        =
    // ======================================

    public List<String> getThreadStack() {
        StackTraceElement[] stackTraceElements = Thread.currentThread().getStackTrace();
        List<String> elements = new ArrayList<>();
        for (StackTraceElement stackTraceElement : stackTraceElements) {
            elements.add(stackTraceElement.getClassName() + "." +
                    stackTraceElement.getMethodName() +
                    "(" + stackTraceElement.getFileName() + ":" + stackTraceElement.getLineNumber() + ")");
        }
        return elements;
    }

    public String getWorkingDirectory() {
        return new java.io.File(".").getAbsolutePath();
    }

    public String getTotalMemory() {
        return String.valueOf(Runtime.getRuntime().totalMemory());
    }

    public String getFreeMemory() {
        return String.valueOf(Runtime.getRuntime().freeMemory());
    }
}

src/main/java/org/agoncal/application/petstore/view/LocaleBean.java
package org.agoncal.application.petstore.view;

import org.agoncal.application.petstore.util.Loggable;

import javax.enterprise.context.SessionScoped;
import javax.enterprise.inject.Produces;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import java.io.Serializable;
import java.util.Locale;

/**
 * @author Antonio Goncalves
 *         http://www.antoniogoncalves.org
 *         --
 */

@Named
@SessionScoped
@Loggable
public class LocaleBean implements Serializable {

    @Produces
    private Locale locale = FacesContext.getCurrentInstance().getViewRoot().getLocale();

    // ======================================
    // =          Business methods          =
    // ======================================

    public Locale getLocale() {
        return locale;
    }

    public String getLanguage() {
        return locale.getLanguage();
    }

    public void setLanguage(String language) {
        locale = new Locale(language);
        FacesContext.getCurrentInstance().getViewRoot().setLocale(locale);
    }
}

src/main/java/org/agoncal/application/petstore/view/admin/CategoryBean.java
package org.agoncal.application.petstore.view.admin;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;
import javax.ejb.SessionContext;
import javax.ejb.Stateful;
import javax.enterprise.context.Conversation;
import javax.enterprise.context.ConversationScoped;
import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.PersistenceContextType;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.agoncal.application.petstore.model.Category;
import org.agoncal.application.petstore.util.Loggable;

/**
 * Backing bean for Category entities.
 * <p/>
 * This class provides CRUD functionality for all Category entities. It focuses
 * purely on Java EE 6 standards (e.g. <tt>&#64;ConversationScoped</tt> for
 * state management, <tt>PersistenceContext</tt> for persistence,
 * <tt>CriteriaBuilder</tt> for searches) rather than introducing a CRUD framework or
 * custom base class.
 */

@Named
@Stateful
@ConversationScoped
@Loggable
public class CategoryBean implements Serializable
{

   private static final long serialVersionUID = 1L;

   /*
    * Support creating and retrieving Category entities
    */

   private Long id;

   public Long getId()
   {
      return this.id;
   }

   public void setId(Long id)
   {
      this.id = id;
   }

   private Category category;

   public Category getCategory()
   {
      return this.category;
   }

   public void setCategory(Category category)
   {
      this.category = category;
   }

   @Inject
   private Conversation conversation;

   @PersistenceContext(unitName = "applicationPetstorePU", type = PersistenceContextType.EXTENDED)
   private EntityManager entityManager;

   public String create()
   {

      this.conversation.begin();
      this.conversation.setTimeout(1800000L);
      return "create?faces-redirect=true";
   }

   public void retrieve()
   {

      if (FacesContext.getCurrentInstance().isPostback())
      {
         return;
      }

      if (this.conversation.isTransient())
      {
         this.conversation.begin();
         this.conversation.setTimeout(1800000L);
      }

      if (this.id == null)
      {
         this.category = this.example;
      }
      else
      {
         this.category = findById(getId());
      }
   }

   public Category findById(Long id)
   {

      return this.entityManager.find(Category.class, id);
   }

   /*
    * Support updating and deleting Category entities
    */

   public String update()
   {
      this.conversation.end();

      try
      {
         if (this.id == null)
         {
            this.entityManager.persist(this.category);
            return "search?faces-redirect=true";
         }
         else
         {
            this.entityManager.merge(this.category);
            return "view?faces-redirect=true&id=" + this.category.getId();
         }
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   public String delete()
   {
      this.conversation.end();

      try
      {
         Category deletableEntity = findById(getId());

         this.entityManager.remove(deletableEntity);
         this.entityManager.flush();
         return "search?faces-redirect=true";
      }
      catch (Exception e)
      {
         FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(e.getMessage()));
         return null;
      }
   }

   /*
    * Support searching Category entities with pagination
    */

   private int page;
   private long count;
   private List<Category> pageItems;

   private Category example = new Category();

   public int getPage()
   {
      return this.page;
   }

   public void setPage(int page)
   {
      this.page = page;
   }

   public int getPageSize()
   {
      return 10;
   }

   public Category getExample()
   {
      return this.example;
   }

   public void setExample(Category example)
   {
      this.example = example;
   }

   public String search()
   {
      this.page = 0;
      return null;
   }

   public void paginate()
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();

      // Populate this.count

      CriteriaQuery<Long> countCriteria = builder.createQuery(Long.class);
      Root<Category> root = countCriteria.from(Category.class);
      countCriteria = countCriteria.select(builder.count(root)).where(
            getSearchPredicates(root));
      this.count = this.entityManager.createQuery(countCriteria)
            .getSingleResult();

      // Populate this.pageItems

      CriteriaQuery<Category> criteria = builder.createQuery(Category.class);
      root = criteria.from(Category.class);
      TypedQuery<Category> query = this.entityManager.createQuery(criteria
            .select(root).where(getSearchPredicates(root)));
      query.setFirstResult(this.page * getPageSize()).setMaxResults(
            getPageSize());
      this.pageItems = query.getResultList();
   }

   private Predicate[] getSearchPredicates(Root<Category> root)
   {

      CriteriaBuilder builder = this.entityManager.getCriteriaBuilder();
      List<Predicate> predicatesList = new ArrayList<Predicate>();

      String name = this.example.getName();
      if (name != null && !"".equals(name))
      {
         predicatesList.add(builder.like(builder.lower(root.<String> get("name")), '%' + name.toLowerCase() + '%'));
      }
      String description = this.example.getDescription();
      if (description != null && !"".equals(description))
      {
         predicatesList.add(builder.like(builder.lower(root.<String> get("description")), '%' + description.toLowerCase() + '%'));
      }

      return predicatesList.toArray(new Predicate[predicatesList.size()]);
   }

   public List<Category> getPageItems()
   {
      return this.pageItems;
   }

   public long getCount()
   {
      return this.count;
   }

   /*
    * Support listing and POSTing back Category entities (e.g. from inside an
    * HtmlSelectOneMenu)
    */

   public List<Category> getAll()
   {

      CriteriaQuery<Category> criteria = this.entityManager
            .getCriteriaBuilder().createQuery(Category.class);
      return this.entityManager.createQuery(
            criteria.select(criteria.from(Category.class))).getResultList();
   }

   @Resource
   private SessionContext sessionContext;

   public Converter getConverter()
   {

      final CategoryBean ejbProxy = this.sessionContext.getBusinessObject(CategoryBean.class);

      return new Converter()
      {

         @Override
         public Object getAsObject(FacesContext context,
               UIComponent component, String value)
         {

            return ejbProxy.findById(Long.valueOf(value));
         }

         @Override
         public String getAsString(FacesContext context,
               UIComponent component, Object value)
         {

            if (value == null)
            {
               return "";
            }

            return String.valueOf(((Category) value).getId());
         }
      };
   }

   /*
    * Support adding children to bidirectional, one-to-many tables
    */

   private Category add = new Category();

   public Category getAdd()
   {
      return this.add;
   }

   public Category getAdded()
   {
      Category added = this.add;
      this.add = new Category();
      return added;
   }
}

src/main/webapp/debug.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE composition PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
                xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
                xmlns:h="http://xmlns.jcp.org/jsf/html"
                xmlns:pt="http://xmlns.jcp.org/jsf/passthrough"
                template="/resources/templates/templateShopping.xhtml">

    <ui:param name="pageTitle" value="Debug"/>

    <ui:define name="main">

        <h2>Request information</h2>

        <h:panelGrid columns="2">
            <h:outputLabel value="Protocol"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getProtocol()}"/>
            <h:outputLabel value="ContentType"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getContentType()}"/>
            <h:outputLabel value="RemoteAddr"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getRemoteAddr()}"/>
            <h:outputLabel value="RemoteHost"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getRemoteHost()}"/>
            <h:outputLabel value="Scheme"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getScheme()}"/>
            <h:outputLabel value="ServerName"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getServerName()}"/>
            <h:outputLabel value="ServerPort"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getServerPort()}"/>
            <h:outputLabel value="AuthType"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getAuthType()}"/>
            <h:outputLabel value="ContextPath"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getContextPath()}"/>
            <h:outputLabel value="Method"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getMethod()}"/>
            <h:outputLabel value="PathInfo"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getPathInfo()}"/>
            <h:outputLabel value="PathTranslated"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getPathTranslated()}"/>
            <h:outputLabel value="QueryString"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getQueryString()}"/>
            <h:outputLabel value="RemoteUser"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getRemoteUser()}"/>
            <h:outputLabel value="RequestedSessionId"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getRequestedSessionId()}"/>
            <h:outputLabel value="RequestURI"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getRequestURI()}" size="60"/>
            <h:outputLabel value="RequestURL"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getRequestURL()}"/>
            <h:outputLabel value="ServletPath"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getServletPath()}"/>
            <h:outputLabel value="ServerName"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getServerName()}"/>
            <h:outputLabel value="ServerPort"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.getServerPort()}"/>
            <h:outputLabel value="isRequestedSessionIdFromCookie"/>
            <h:outputText class="form-control" pt:disabled="disabled"
                          value="#{request.isRequestedSessionIdFromCookie()}"/>
            <h:outputLabel value="isRequestedSessionIdFromURL"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.isRequestedSessionIdFromURL()}"/>
            <h:outputLabel value="isRequestedSessionIdValid"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.isRequestedSessionIdValid()}"/>
            <h:outputLabel value="isSecure"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{request.isSecure()}"/>
        </h:panelGrid>
        <br/>

        <h2>Request headers</h2>
        <h:panelGrid columns="2">
            <c:forEach items="#{headerValues}" var="entry">
                <h:outputLabel value="#{entry.key}"/>
                <c:forEach items="#{entry.value}" var="headerValue">
                    <h:inputText class="form-control" pt:disabled="disabled" value="#{headerValue}" size="82"/>
                </c:forEach>
            </c:forEach>
        </h:panelGrid>

        <h2>Request cookies</h2>
        <h:panelGrid columns="2">
            <c:forEach items="#{cookie}" var="entry">
                <h:outputLabel value="#{entry.key}"/>
                <h:outputText class="form-control" pt:disabled="disabled" value="#{entry.value.value}" size="82"/>
            </c:forEach>
        </h:panelGrid>

        <h2>Request attributes</h2>
        <h:panelGrid columns="2">
            <c:forEach items="#{requestScope}" var="entry">
                <h:outputLabel value="#{entry.key}" />
                <h:inputText class="form-control" pt:disabled="disabled" value="#{entry.value}" />
            </c:forEach>
        </h:panelGrid>

        <h2>Session information</h2>
        <h:panelGrid columns="2">
            <h:outputLabel value="MaxInactiveInterval (min)"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{session.getMaxInactiveInterval() / 60}"/>
            <h:outputLabel value="Id"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{session.getId()}" size="72"/>
            <h:outputLabel value="LastAccessedTime"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{session.getLastAccessedTime()}"/>
        </h:panelGrid>

        <h2>Session attributes</h2>
        <h:panelGrid columns="2">
            <c:forEach items="#{sessionScope}" var="entry">
                <h:outputLabel value="#{entry.key}" />
                <h:inputText class="form-control" pt:disabled="disabled" value="#{entry.value}" />
            </c:forEach>
        </h:panelGrid>

        <h2>Application information</h2>
        <h:panelGrid columns="2">
            <h:outputLabel value="ServletContextPath"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{application.getContextPath()}"
                          size="76"/>
            <h:outputLabel value="ServletContextName"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{application.getServletContextName()}"/>
            <h:outputLabel value="MajorVersion"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{application.getMajorVersion()}"/>
            <h:outputLabel value="MinorVersion"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{application.getMinorVersion()}"/>
            <h:outputLabel value="ServerInfo"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{application.getServerInfo()}"/>
            <h:outputLabel value="ResourceUrlForSlash"/>
            <h:inputText class="form-control" pt:disabled="disabled" value="#{application.getResource('/')}" size="80"/>
        </h:panelGrid>

        <h2>Application attributes</h2>
        <h:panelGrid columns="2">
            <c:forEach items="#{applicationScope}" var="entry">
                <h:outputLabel value="#{entry.key}" />
                <h:inputText class="form-control" pt:disabled="disabled" value="#{entry.value}" />
            </c:forEach>
        </h:panelGrid>

        <h2>System information</h2>
        <h:panelGrid columns="2">
            <h:outputLabel value="Working directory"/>
            <h:inputText class="form-control" pt:disabled="disabled" value="#{debugBean.workingDirectory}"
                          size="64"/>
            <h:outputLabel value="InetAddress.getLocalHost()"/>
            <h:inputText class="form-control" pt:disabled="disabled" value="#{debugBean.workingDirectory}"/>
            <h:outputLabel value="InetAddress.getAllByName(null)"/>
            <h:inputText class="form-control" pt:disabled="disabled" value="#{debugBean.workingDirectory}"/>
        </h:panelGrid>

        <h2>Memory</h2>
        <h:panelGrid columns="2">
            <h:outputLabel value="Total Memory"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{debugBean.totalMemory}" size="64"/>
            <h:outputLabel value="Free Memory"/>
            <h:outputText class="form-control" pt:disabled="disabled" value="#{debugBean.freeMemory}"/>
        </h:panelGrid>

        <h2>Thread stack</h2>
        <h:panelGrid columns="1">
            <c:forEach items="#{debugBean.threadStack}" var="entry">
                <h:outputLabel value="#{entry}" />
            </c:forEach>
        </h:panelGrid>


    </ui:define>
</ui:composition>

src/main/webapp/error.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/resources/scaffold/pageTemplate.xhtml">

	<ui:param name="pageTitle" value="Server error" />

	<ui:define name="header">
		Oops
	</ui:define>

	<ui:define name="subheader">
		That's going to leave a mark!
	</ui:define>

	<ui:define name="main">
		<p style="text-align: right; padding-top: 150px">
			<a target="_blank" href="http://jboss.org"><img
				src='#{resource["jboss-community.png"]}'
				alt="JBoss and JBoss Community" width="254" height="31" border="0" />
			</a> <br /> To replace this page edit 'src/main/webapp/error.xhtml', or
			keep Forging!
		</p>
	</ui:define>

</ui:composition>